from .gminaSerializer import GminaSerializer
from .kandydatSerializer import KandydatSerializer
from .wojewodztwoSerializer import WojewodztwoSerializer
from .rodzajSerializer import RodzajSerializer
