# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gmina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200, unique=True)),
                ('liczbaMieszkancow', models.IntegerField()),
                ('liczbaUprawnionych', models.IntegerField()),
                ('liczbaWydanychKart', models.IntegerField()),
                ('liczbaGlosowOddanych', models.IntegerField()),
                ('liczbaGlosowWaznych', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kandydat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwisko', models.CharField(max_length=50)),
                ('imiona', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RodzajGminy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wojewodztwo',
            fields=[
                ('numer', models.IntegerField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='gmina',
            name='rodzaj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.RodzajGminy'),
        ),
        migrations.AddField(
            model_name='gmina',
            name='wojewodztwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Wojewodztwo'),
        ),
    ]
