# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kandydat',
            name='numer',
            field=models.IntegerField(choices=[(1, '1'), (2, '2')], default=1, unique=True),
            preserve_default=False,
        ),
    ]
