# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_auto_20160328_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='wojewodztwo',
            name='hckey',
            field=models.CharField(default='hc-x', max_length=15),
            preserve_default=False,
        ),
    ]
