# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_wojewodztwo_hckey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmina',
            name='liczbaGlosowKand1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gmina',
            name='liczbaGlosowKand2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gmina',
            name='liczbaGlosowOddanych',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gmina',
            name='liczbaGlosowWaznych',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gmina',
            name='liczbaMieszkancow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gmina',
            name='liczbaUprawnionych',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gmina',
            name='liczbaWydanychKart',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gmina',
            name='nazwa',
            field=models.CharField(max_length=200),
        ),
    ]
