# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 11:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('election', '0006_wojewodztwo_hckey'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmina',
            name='rev',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gmina',
            name='revtime',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 9, 11, 6, 32, 548215, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gmina',
            name='revuser',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gmina',
            name='liczbaGlosowKand1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gmina',
            name='liczbaGlosowKand2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gmina',
            name='liczbaGlosowOddanych',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gmina',
            name='liczbaGlosowWaznych',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gmina',
            name='liczbaMieszkancow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gmina',
            name='liczbaUprawnionych',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gmina',
            name='liczbaWydanychKart',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gmina',
            name='nazwa',
            field=models.CharField(max_length=200),
        ),
    ]
