# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_auto_20160408_1257'),
        ('election', '0007_auto_20160509_1306'),
    ]

    operations = [
    ]
